### ISSUE TITLE
Account Index Generator Crashes in Organizations with Nested OUs

### ISSUE THREAD

**Issue by ericwestfall** [gemini-oss/starfleet#24]
## Description

The `AccountIndexGeneratorShip` experiences an unhandled `KeyError` exception and subsequent fatal crash when attempting to generate the account inventory when deployed in an organization with a nested OU hierarchy. 

```shell
Root (r-olgb)
├── Core Infrastructure (ou-olgb-q97w37sn)
│   ├── Prod (ou-olgb-7puk9u2d)
│   │   ├── secops-account-prod (123456789012)
├── Workloads (ou-olgb-e604f59w)
│   ├── Prod (ou-olgb-q8z9vop9)
│   │   ├── auth-service-account-prod (123456789033)
│   ├── Non-Prod (ou-olgb-nndadfrq)
├── org-managment-account-prod (123456789441)
```
_Fig 1. An example organization structure with a valid nested OU hierarchy._

## Expected Behavior

The `AccountIndexGeneratorShip` should be capable of successfully generating an account inventory when deployed in any valid environment that adheres to AWS Organizations standards and service quota limits.

## Actual Behavior

With the `AccountIndexGeneratorShip` deployed correctly in an organization that includes a nested OU hierarchy (see Figure 1 above), executing the `starfleet account-inventory generate` command throws an unhandled `KeyError` exception  resulting in a fatal crash of the `AccountIndexGeneratorShip` and no account inventory output.

```shell
starfleet on main [$] is 📦 v0.0.1 via 🐍 v3.9.16 (starfleet) on ☁️  aws-security-research-lab-secops-admin (us-east-2)
❯ starfleet account-inventory generate \
  --commit \
  --payload SaveAccountInventory.yaml

[...]
[🆗] Template OK: Executing worker: AccountIndexGeneratorShip...
2023-05-08 17:52:15,401 - INFO - [📡] Reaching out to the Orgs API to get the list of AWS accounts in account: <REDACTED>... - /Users/erwestfa/projects/oss/starfleet/src/starfleet/worker_ships/plugins/account_index_generator/ship.py - execute:61
2023-05-08 17:52:17,325 - INFO - [📡] Reaching out to the Orgs API to get the list of all OUs in the org... - /Users/erwestfa/projects/oss/starfleet/src/starfleet/worker_ships/plugins/account_index_generator/ship.py - execute:68
2023-05-08 17:52:18,375 - INFO - [🚚] Fetching tags and enabled regions for each account... - /Users/erwestfa/projects/oss/starfleet/src/starfleet/worker_ships/plugins/account_index_generator/ship.py - execute:76
[...]
2023-05-08 17:52:20,706 - DEBUG - [👪] Fetching parents for account id: <REDACTED>... - /Users/erwestfa/projects/oss/starfleet/src/starfleet/worker_ships/plugins/account_index_generator/utils.py - fetch_tags_and_parents:81
Traceback (most recent call last):
  File "/Users/erwestfa/.pyenv/versions/starfleet/bin/starfleet", line 8, in <module>
    sys.exit(cli())
  File "/Users/erwestfa/projects/oss/starfleet/src/starfleet/worker_ships/plugins/account_index_generator/ship.py", line 120, in generate
    worker.execute(commit=commit)
  File "/Users/erwestfa/projects/oss/starfleet/src/starfleet/worker_ships/plugins/account_index_generator/ship.py", line 77, in execute
    fetch_additional_details(
  File "/Users/erwestfa/projects/oss/starfleet/src/starfleet/worker_ships/plugins/account_index_generator/utils.py", line 168, in fetch_additional_details
    parent_ous.append({"Id": parent["Id"], "Type": parent["Type"], "Name": all_ous[parent["Id"]]})
KeyError: 'ou-olgb-q8z9vop9'
```
_Fig 2. Account inventory generate command output showing unhandled exception._

## Steps to Reproduce

1. In the target environment where Starfleet will be deployed, ensure the organization has at least one member account that is contained within a nested OU hierarchy with a minimum of 2 levels of OU nesting (see Figure 1 above for more detail). 

2. Deploy Starfleet to a delegated member account in accordance with the [installation guide](https://gemini-oss.github.io/starfleet/installation/Overview/). 

3. Using the CLI, trigger a new account inventory generation tasking:
   ```shell
   starfleet account-inventory generate \
      --commit \
      --payload SaveAccountInventory.yaml
   ```

## Root Cause

The `AccountIndexGeneratorShip` executes the AWS Organizations `ListOrganizationalUnitsForParent` API call, passing the organization root ID to the `ParentId` request parameter, which returns only the top-level OUs under the root. However, the `AccountIndexGeneratorShip` never recursively checks if the top-level OUs contain any nested OUs.

https://github.com/gemini-oss/starfleet/blob/3d495f1af8cea0e0526e0dc1a97793e66453b932/src/starfleet/worker_ships/plugins/account_index_generator/ship.py#L67-L73

The results of this API call are then used to generate a map of OU names keyed to their respective OU identifiers. This map is passed to an asynchronous utility function `fetch_additional_details()` that retrieves additional metadata about member accounts. As this function iterates over member accounts, it references the map to retrieve the friendly name of the OU that contains the account, assuming the identifier exists in the map. 

https://github.com/gemini-oss/starfleet/blob/3d495f1af8cea0e0526e0dc1a97793e66453b932/src/starfleet/worker_ships/plugins/account_index_generator/utils.py#L159-L174

In the scenario where the member account is contained in an OU that is nested one or more levels below the top-level OUs under the root, the OU identifier that contains the member account will **_not_** be in the map, resulting in the unhandled `KeyError` exception. 

## Additional Information and Context 

```shell
starfleet on main [$] is 📦 v0.0.1 via 🐍 v3.9.16 (starfleet) on ☁️  aws-security-research-lab-secops-admin (us-east-2)
❯ starfleet account-inventory generate \
  --commit \
  --payload SaveAccountInventory.yaml

                _/                              _/_/  _/                        _/
     _/_/_/  _/_/_/_/    _/_/_/  _/  _/_/    _/      _/    _/_/      _/_/    _/_/_/_/
  _/_/        _/      _/    _/  _/_/      _/_/_/_/  _/  _/_/_/_/  _/_/_/_/    _/
     _/_/    _/      _/    _/  _/          _/      _/  _/        _/          _/
_/_/_/        _/_/    _/_/_/  _/          _/      _/    _/_/_/    _/_/_/      _/_/

2023-05-08 17:52:15,218 - DEBUG - [📄] Loading the base configuration from /Users/erwestfa/projects/oss/starfleet/src/starfleet/configuration_files... - /Users/erwestfa/projects/oss/starfleet/src/starfleet/utils/configuration.py - load_base_configuration:43
2023-05-08 17:52:15,218 - DEBUG - [⚙️] Processing configuration file: configuration.yaml... - /Users/erwestfa/projects/oss/starfleet/src/starfleet/utils/configuration.py - load_base_configuration:49
2023-05-08 17:52:15,223 - DEBUG - [⚙️] Successfully loaded configuration file: configuration.yaml - /Users/erwestfa/projects/oss/starfleet/src/starfleet/utils/configuration.py - load_base_configuration:56
2023-05-08 17:52:15,225 - DEBUG - [🪵] Configuring the logger for the rest of the application... - /Users/erwestfa/projects/oss/starfleet/src/starfleet/utils/configuration.py - load_base_configuration:74
2023-05-08 17:52:15,225 - DEBUG - [🆗️] Base configuration loaded successfully - /Users/erwestfa/projects/oss/starfleet/src/starfleet/utils/configuration.py - load_base_configuration:83
2023-05-08 17:52:15,225 - DEBUG - [📦] Loading worker ship plugins... - /Users/erwestfa/projects/oss/starfleet/src/starfleet/worker_ships/loader.py - load_all_plugins:44
2023-05-08 17:52:15,225 - DEBUG - [🏗️] Loading plugins in the ['/Users/erwestfa/projects/oss/starfleet/src/starfleet/worker_ships/plugins'] location... - /Users/erwestfa/projects/oss/starfleet/src/starfleet/utils/plugin_loader.py - find_plugins:40
2023-05-08 17:52:15,226 - DEBUG - [⚙️] Processing module named: starfleet.worker_ships.plugins.account_index_generator - /Users/erwestfa/projects/oss/starfleet/src/starfleet/utils/plugin_loader.py - find_plugins:42
2023-05-08 17:52:15,242 - DEBUG - [👍] Found 1 plugins in ['/Users/erwestfa/projects/oss/starfleet/src/starfleet/worker_ships/plugins'] - /Users/erwestfa/projects/oss/starfleet/src/starfleet/utils/plugin_loader.py - find_plugins:61
2023-05-08 17:52:15,242 - DEBUG - [⚙️] Processing module named: starfleet.worker_ships.plugins.aws_config - /Users/erwestfa/projects/oss/starfleet/src/starfleet/utils/plugin_loader.py - find_plugins:42
2023-05-08 17:52:15,296 - DEBUG - [👍] Found 1 plugins in ['/Users/erwestfa/projects/oss/starfleet/src/starfleet/worker_ships/plugins'] - /Users/erwestfa/projects/oss/starfleet/src/starfleet/utils/plugin_loader.py - find_plugins:61
2023-05-08 17:52:15,296 - DEBUG - [⚙️] Processing module named: starfleet.worker_ships.plugins.github_sync - /Users/erwestfa/projects/oss/starfleet/src/starfleet/utils/plugin_loader.py - find_plugins:42
2023-05-08 17:52:15,398 - DEBUG - [👍] Found 1 plugins in ['/Users/erwestfa/projects/oss/starfleet/src/starfleet/worker_ships/plugins'] - /Users/erwestfa/projects/oss/starfleet/src/starfleet/utils/plugin_loader.py - find_plugins:61
2023-05-08 17:52:15,398 - DEBUG - [🔧] Configuring worker ship: AccountIndexGeneratorShip - /Users/erwestfa/projects/oss/starfleet/src/starfleet/worker_ships/loader.py - load_all_plugins:48
2023-05-08 17:52:15,398 - DEBUG - [👍] Worker ship: AccountIndexGeneratorShip is properly configured and ENABLED. - /Users/erwestfa/projects/oss/starfleet/src/starfleet/worker_ships/loader.py - load_all_plugins:65
2023-05-08 17:52:15,398 - DEBUG - [🔧] Configuring worker ship: AwsConfigWorkerShip - /Users/erwestfa/projects/oss/starfleet/src/starfleet/worker_ships/loader.py - load_all_plugins:48
2023-05-08 17:52:15,399 - DEBUG - [⏭️] Worker ship: AwsConfigWorkerShip has no discovered configuration. Skipping...  - /Users/erwestfa/projects/oss/starfleet/src/starfleet/worker_ships/loader.py - load_all_plugins:68
2023-05-08 17:52:15,399 - DEBUG - [🔧] Configuring worker ship: GitHubSyncWorkerShip - /Users/erwestfa/projects/oss/starfleet/src/starfleet/worker_ships/loader.py - load_all_plugins:48
2023-05-08 17:52:15,399 - DEBUG - [⏭️] Worker ship: GitHubSyncWorkerShip has no discovered configuration. Skipping...  - /Users/erwestfa/projects/oss/starfleet/src/starfleet/worker_ships/loader.py - load_all_plugins:68
2023-05-08 17:52:15,399 - DEBUG - [🚀] Completed loading 1 worker ships - /Users/erwestfa/projects/oss/starfleet/src/starfleet/worker_ships/loader.py - load_all_plugins:79
2023-05-08 17:52:15,399 - DEBUG - [🖥️] Loading CLIs (which are just plugins)... - /Users/erwestfa/projects/oss/starfleet/src/starfleet/cli/components.py - load_clis:43
2023-05-08 17:52:15,399 - DEBUG - [🏗️] Loading plugins in the ['/Users/erwestfa/projects/oss/starfleet/src/starfleet/worker_ships/plugins'] location... - /Users/erwestfa/projects/oss/starfleet/src/starfleet/utils/plugin_loader.py - find_plugins:40
2023-05-08 17:52:15,399 - DEBUG - [⚙️] Processing module named: starfleet.worker_ships.plugins.account_index_generator - /Users/erwestfa/projects/oss/starfleet/src/starfleet/utils/plugin_loader.py - find_plugins:42
2023-05-08 17:52:15,399 - DEBUG - [👍] Found 1 plugins in ['/Users/erwestfa/projects/oss/starfleet/src/starfleet/worker_ships/plugins'] - /Users/erwestfa/projects/oss/starfleet/src/starfleet/utils/plugin_loader.py - find_plugins:61
2023-05-08 17:52:15,399 - DEBUG - [⚙️] Processing module named: starfleet.worker_ships.plugins.aws_config - /Users/erwestfa/projects/oss/starfleet/src/starfleet/utils/plugin_loader.py - find_plugins:42
2023-05-08 17:52:15,399 - DEBUG - [👍] Found 1 plugins in ['/Users/erwestfa/projects/oss/starfleet/src/starfleet/worker_ships/plugins'] - /Users/erwestfa/projects/oss/starfleet/src/starfleet/utils/plugin_loader.py - find_plugins:61
2023-05-08 17:52:15,399 - DEBUG - [⚙️] Processing module named: starfleet.worker_ships.plugins.github_sync - /Users/erwestfa/projects/oss/starfleet/src/starfleet/utils/plugin_loader.py - find_plugins:42
2023-05-08 17:52:15,399 - DEBUG - [👍] Found 1 plugins in ['/Users/erwestfa/projects/oss/starfleet/src/starfleet/worker_ships/plugins'] - /Users/erwestfa/projects/oss/starfleet/src/starfleet/utils/plugin_loader.py - find_plugins:61
2023-05-08 17:52:15,399 - DEBUG - [🖥️] Completed loading 3 CLIs - /Users/erwestfa/projects/oss/starfleet/src/starfleet/cli/components.py - load_clis:48
[🛃] Validating the template...
[🆗] Template OK: Executing worker: AccountIndexGeneratorShip...
2023-05-08 17:52:15,401 - INFO - [📡] Reaching out to the Orgs API to get the list of AWS accounts in account: <REDACTED>... - /Users/erwestfa/projects/oss/starfleet/src/starfleet/worker_ships/plugins/account_index_generator/ship.py - execute:61
2023-05-08 17:52:17,325 - INFO - [📡] Reaching out to the Orgs API to get the list of all OUs in the org... - /Users/erwestfa/projects/oss/starfleet/src/starfleet/worker_ships/plugins/account_index_generator/ship.py - execute:68
2023-05-08 17:52:18,375 - INFO - [🚚] Fetching tags and enabled regions for each account... - /Users/erwestfa/projects/oss/starfleet/src/starfleet/worker_ships/plugins/account_index_generator/ship.py - execute:76
2023-05-08 17:52:19,894 - DEBUG - [🏷️] Fetching tags for account id: <REDACTED>... - /Users/erwestfa/projects/oss/starfleet/src/starfleet/worker_ships/plugins/account_index_generator/utils.py - fetch_tags_and_parents:70
2023-05-08 17:52:19,895 - DEBUG - [🌍️] Fetching enabled regions for account id: <REDACTED>... - /Users/erwestfa/projects/oss/starfleet/src/starfleet/worker_ships/plugins/account_index_generator/utils.py - fetch_regions:91
2023-05-08 17:52:19,898 - DEBUG - [🏷️] Fetching tags for account id: <REDACTED>... - /Users/erwestfa/projects/oss/starfleet/src/starfleet/worker_ships/plugins/account_index_generator/utils.py - fetch_tags_and_parents:70
2023-05-08 17:52:19,899 - DEBUG - [🌍️] Fetching enabled regions for account id: <REDACTED>... - /Users/erwestfa/projects/oss/starfleet/src/starfleet/worker_ships/plugins/account_index_generator/utils.py - fetch_regions:91
2023-05-08 17:52:19,899 - DEBUG - [🏷️] Fetching tags for account id: <REDACTED>... - /Users/erwestfa/projects/oss/starfleet/src/starfleet/worker_ships/plugins/account_index_generator/utils.py - fetch_tags_and_parents:70
2023-05-08 17:52:19,906 - DEBUG - [🌍️] Fetching enabled regions for account id: <REDACTED>... - /Users/erwestfa/projects/oss/starfleet/src/starfleet/worker_ships/plugins/account_index_generator/utils.py - fetch_regions:91
2023-05-08 17:52:19,907 - DEBUG - [🏷️] Fetching tags for account id: <REDACTED>... - /Users/erwestfa/projects/oss/starfleet/src/starfleet/worker_ships/plugins/account_index_generator/utils.py - fetch_tags_and_parents:70
2023-05-08 17:52:19,910 - DEBUG - [🌍️] Fetching enabled regions for account id: <REDACTED>... - /Users/erwestfa/projects/oss/starfleet/src/starfleet/worker_ships/plugins/account_index_generator/utils.py - fetch_regions:91
2023-05-08 17:52:19,911 - DEBUG - [🏷️] Fetching tags for account id: <REDACTED>... - /Users/erwestfa/projects/oss/starfleet/src/starfleet/worker_ships/plugins/account_index_generator/utils.py - fetch_tags_and_parents:70
2023-05-08 17:52:19,915 - DEBUG - [🌍️] Fetching enabled regions for account id: <REDACTED>... - /Users/erwestfa/projects/oss/starfleet/src/starfleet/worker_ships/plugins/account_index_generator/utils.py - fetch_regions:91
2023-05-08 17:52:19,921 - DEBUG - [🏷️] Fetching tags for account id: <REDACTED>... - /Users/erwestfa/projects/oss/starfleet/src/starfleet/worker_ships/plugins/account_index_generator/utils.py - fetch_tags_and_parents:70
2023-05-08 17:52:19,927 - DEBUG - [🌍️] Fetching enabled regions for account id: <REDACTED>... - /Users/erwestfa/projects/oss/starfleet/src/starfleet/worker_ships/plugins/account_index_generator/utils.py - fetch_regions:91
2023-05-08 17:52:19,930 - DEBUG - [🏷️] Fetching tags for account id: <REDACTED>... - /Users/erwestfa/projects/oss/starfleet/src/starfleet/worker_ships/plugins/account_index_generator/utils.py - fetch_tags_and_parents:70
2023-05-08 17:52:19,931 - DEBUG - [🌍️] Fetching enabled regions for account id: <REDACTED>... - /Users/erwestfa/projects/oss/starfleet/src/starfleet/worker_ships/plugins/account_index_generator/utils.py - fetch_regions:91
2023-05-08 17:52:20,630 - DEBUG - [👪] Fetching parents for account id: <REDACTED>... - /Users/erwestfa/projects/oss/starfleet/src/starfleet/worker_ships/plugins/account_index_generator/utils.py - fetch_tags_and_parents:81
2023-05-08 17:52:20,633 - DEBUG - [👪] Fetching parents for account id: <REDACTED>... - /Users/erwestfa/projects/oss/starfleet/src/starfleet/worker_ships/plugins/account_index_generator/utils.py - fetch_tags_and_parents:81
2023-05-08 17:52:20,666 - DEBUG - [👪] Fetching parents for account id: <REDACTED>... - /Users/erwestfa/projects/oss/starfleet/src/starfleet/worker_ships/plugins/account_index_generator/utils.py - fetch_tags_and_parents:81
2023-05-08 17:52:20,700 - DEBUG - [👪] Fetching parents for account id: <REDACTED>... - /Users/erwestfa/projects/oss/starfleet/src/starfleet/worker_ships/plugins/account_index_generator/utils.py - fetch_tags_and_parents:81
2023-05-08 17:52:20,702 - DEBUG - [👪] Fetching parents for account id: <REDACTED>... - /Users/erwestfa/projects/oss/starfleet/src/starfleet/worker_ships/plugins/account_index_generator/utils.py - fetch_tags_and_parents:81
2023-05-08 17:52:20,705 - DEBUG - [👪] Fetching parents for account id: <REDACTED>... - /Users/erwestfa/projects/oss/starfleet/src/starfleet/worker_ships/plugins/account_index_generator/utils.py - fetch_tags_and_parents:81
2023-05-08 17:52:20,706 - DEBUG - [👪] Fetching parents for account id: <REDACTED>... - /Users/erwestfa/projects/oss/starfleet/src/starfleet/worker_ships/plugins/account_index_generator/utils.py - fetch_tags_and_parents:81
Traceback (most recent call last):
  File "/Users/erwestfa/.pyenv/versions/starfleet/bin/starfleet", line 8, in <module>
    sys.exit(cli())
  File "/Users/erwestfa/.pyenv/versions/3.9.16/envs/starfleet/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/erwestfa/.pyenv/versions/3.9.16/envs/starfleet/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/erwestfa/.pyenv/versions/3.9.16/envs/starfleet/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/erwestfa/.pyenv/versions/3.9.16/envs/starfleet/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/erwestfa/projects/oss/starfleet/src/starfleet/worker_ships/cli_utils.py", line 137, in invoke
    return super().invoke(ctx)
  File "/Users/erwestfa/.pyenv/versions/3.9.16/envs/starfleet/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/erwestfa/.pyenv/versions/3.9.16/envs/starfleet/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/erwestfa/.pyenv/versions/3.9.16/envs/starfleet/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/erwestfa/projects/oss/starfleet/src/starfleet/worker_ships/plugins/account_index_generator/ship.py", line 120, in generate
    worker.execute(commit=commit)
  File "/Users/erwestfa/projects/oss/starfleet/src/starfleet/worker_ships/plugins/account_index_generator/ship.py", line 77, in execute
    fetch_additional_details(
  File "/Users/erwestfa/projects/oss/starfleet/src/starfleet/worker_ships/plugins/account_index_generator/utils.py", line 168, in fetch_additional_details
    parent_ous.append({"Id": parent["Id"], "Type": parent["Type"], "Name": all_ous[parent["Id"]]})
KeyError: 'ou-olgb-q8z9vop9'
```
_Fig 3. Full stack trace of Starfleet account inventory generation command._

**Comment by ericwestfall** [comment]
Feel free to assign this one to me, I will raise a PR with the fix shortly.

**Comment by mikegrima** [comment]
@ericwestfall Interesting... so basically I need to... for each OU... make a call to the `list_organizational_units_for_parent()` API to see if there are parents in there?

I would just like to add: and please pass this along to the requisite teams: I absolutely **detest** the Orgs API! The fact that we can't easily get a list of all the OUs and their parental relationship is utterly ridiculous!

I'm going to need to figure out how to make these calls recursively... I might need to do some more refactoring to have yet another async call to get these details first and then collect the details about the tags and regions 🤮

**Comment by ericwestfall** [comment]
> I would just like to add: and please pass this along to the requisite teams: I absolutely **detest** the Orgs API! The fact that we can't easily get a list of all the OUs and their parental relationships is utterly ridiculous!

I hear you on that for sure @mikegrima 🤣 

If you can give me a few days, I will send you a PR that refactors the AWS Organizations integration in `Starfleet` to use an AWS Organizations library I developed that provides discovery of accounts and OUs with recursion, fully-qualified path resolution for accounts back to the organization root, and supports attribute-based search (e.g., account name, tags, path, etc.). I have this integration work mostly done over here, just need to clean it up a bit and finish writing tests.

Let me know if you want the PR or prefer to tackle it yourself!

**Comment by mikegrima** [comment]
That works too!

Another thing I could do (and I hate this) is that in this code here:
https://github.com/gemini-oss/starfleet/blob/3d495f1af8cea0e0526e0dc1a97793e66453b932/src/starfleet/worker_ships/plugins/account_index_generator/utils.py#L168

I can make it so that instead of directly referencing the dictionary, I call a function that will attempt to find the OU and if it's not loaded yet, it will lazy load the OU name in. It would work it's just annoying.

**Comment by mikegrima** [comment]
@ericwestfall Friendly ping. I am planning on starting to work on this tomorrow so this can be wrapped up by fwd:cloudsec 2023.

**Comment by mikegrima** [comment]
@ericwestfall do me a favor and run the code I have in that draft PR and let me know if that fixes the issue for you

**Comment by ericwestfall** [comment]
> @ericwestfall do me a favor and run the code I have in that draft PR and let me know if that fixes the issue for you

Hey @mikegrima, while the change in #53 correctly resolves the name of the OU that is the direct parent of an account, even when the OU is missing from the top-level OU map, we are still not recursively resolving the path from the account all the way back to the root. This means the resulting account index will only contain the root and the direct parent which contains the account, but will be missing any intermediary ancestors between the root and the direct parent OU.

AWS Organizations supports nesting of OUs up to 5 levels deep within a root, which is to say the depth of any given account is bounded by the constraint $`1 <= d <= 6`$. 

For a given account whose depth exceeds 2 (e.g., `Root -> Workloads -> Prod -> Account`), the generated account index entry will contain a disjoint path (e.g., `Root -> Prod`) instead of the fully connected path (e.g., `Root -> Workloads -> Prod`).

## Additional Context 

Provided below is the structure of the organization in my research environment:
```
├── Root (r-olqy)
│   ├── Workloads (ou-olqy-e604f59w)
│   │   ├── Non-Prod (ou-olqy-nndadfrq)
│   │   │   ├── aws-security-research-lab-workload-dev (712861421548)
│   │   ├── Prod (ou-olqy-q8z9vop9)
│   │   │   ├── aws-security-research-lab-workload-prod (228001810812)
│   ├── Core Infrastructure (ou-olqy-q97w37sn)
│   │   ├── aws-security-research-lab-devops (629225780623)
│   │   ├── aws-security-research-lab-network (896367252297)
│   │   ├── aws-security-research-lab-secops (150958791683)
│   ├── Sandbox (ou-olqy-7puk9u2d)
│   ├── Security (ou-olqy-u144jfki)
│   │   ├── Audit (950175702822)
│   │   ├── Log Archive (240561585551)
└── aws-security-research-lab-management (401643647498)
```

For a given AWS account `228001810812` ($`d=3`$), this is the resulting account index entry generated (code at revision 8405d19b3d034fcd288ef6f5b02e42a01260f627) which contains a disjoint path in the `Parents` attribute:
```json
{
  "228001810812": {
    "Id": "228001810812",
    "Arn": "arn:aws:organizations::401643647498:account/o-qsujwb57n9/228001810812",
    "Email": "erwestfa+aws-security-research-lab-workload-prod@amazon.com",
    "Name": "aws-security-research-lab-workload-prod",
    "Status": "ACTIVE",
    "JoinedMethod": "CREATED",
    "JoinedTimestamp": "2023-03-10 08:52:08.254000-08:00",
    "Tags": {},
    "Parents": [
      {
        "Id": "ou-olqy-q8z9vop9",
        "Type": "ORGANIZATIONAL_UNIT",
        "Name": "Prod"
      },
      {
        "Id": "r-olqy",
        "Type": "ROOT",
        "Name": "ROOT"
      }
    ],
    "Regions": [
      "us-east-1",
      "us-east-2"
    ]
  }
}
```

Ideally, the account index object generated for the account should contain a fully connected path to the root, including all intermediary ancestors between the account's immediate parent and the root: 

```json
{
  "228001810812": {
    "Id": "228001810812",
    "Arn": "arn:aws:organizations::401643647498:account/o-qsujwb57n9/228001810812",
    "Email": "erwestfa+aws-security-research-lab-workload-prod@amazon.com",
    "Name": "aws-security-research-lab-workload-prod",
    "Status": "ACTIVE",
    "JoinedMethod": "CREATED",
    "JoinedTimestamp": "2023-03-10 08:52:08.254000-08:00",
    "Tags": {},
    "Parents": [
      {
        "Id": "ou-olqy-q8z9vop9",
        "Type": "ORGANIZATIONAL_UNIT",
        "Name": "Prod"
      },
      {
        "Id": "ou-olqy-e604f59w",
        "Type": "ORGANIZATIONAL_UNIT",
        "Name": "Workloads"
      },
      {
        "Id": "r-olqy",
        "Type": "ROOT",
        "Name": "ROOT"
      }
    ],
    "Regions": [
      "us-east-1",
      "us-east-2"
    ]
  }
}
```

## Additional Considerations

This also has implications for account resolution. For example, consider a worker that implements an `Account` fan out strategy and needs to resolve the following `IncludeAccounts` payload stanza:

```yaml
IncludeAccounts:
    ByOrgUnits:
        - Workloads
ExcludeAccounts:
    ByNames:
        - aws-security-research-lab-workload-prod
```

Considering the `Workloads` OU contains multiple child OUs and accounts at varying levels, what is the expected behavior and what is the users intent? Should this resolve to all accounts that are contained directly in the `Workloads` OU **_and_** any OUs nested below the `Workloads` OU? 

This requires that we have the capability to resolve the complete subset of accounts for any given path, which is why I was pursuing a broader solution in parallel to this effort. Let me know your thoughts, happy to chat about this in more detail ...

**Comment by mikegrima** [comment]
Yup -- fixing that now

**Comment by mikegrima** [comment]
Question: Does `list_parents` only ever return 1 parent? Why call it `list_parents` and make it paginated for????

**Comment by mikegrima** [comment]
Just updated the PR. I *think* this should finally do it. What a PITA! I'll test internally on Monday just to triple check.

**Comment by mikegrima** [comment]
I have confirmed that the latest changes on that branch will work with nested OUs and everything. Though, please triple check for me if there are any outstanding issues.
